"""
PV1-R: Production vegetation asset generator.

Creates production-quality tree GLB assets using:
- Blender Python API for geometry (trunk + branch system + alpha card foliage)
- Poly Haven CC0 textures (bark diffuse, foliage diffuse+alpha)
- Proper PBR materials with alpha-masked leaf cards
- 3 LOD levels per asset

This is a completely NEW pipeline, independent of the previous Rust procedural
builders (puff_blob, tube_sweep, frond_mesh, etc.).

Asset provenance:
  Textures: Poly Haven (https://polyhaven.com) - CC0 license
  Geometry: Generated by this script (Blender Python API)
  Author: PV1-R processing pipeline
  Date: 2026-09-08

Usage:
  blender --background --python generate_production_trees.py
"""

import bpy
import bmesh
import math
import os
import sys
import json
from mathutils import Vector, Matrix

# ── Configuration ──────────────────────────────────────────────────────────

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TEXTURE_DIR = os.path.join(SCRIPT_DIR, "textures")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "..", "crates", "renderer", "assets", "vegetation")

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Species definitions ────────────────────────────────────────────────────

SPECIES = [
    {
        "name": "pine_a",
        "type": "conifer",
        "texture_dir": os.path.join(TEXTURE_DIR, "pine_tree_01"),
        "bark_tex": "bark_diff_2k.jpg",
        "foliage_tex": "twig_diff_2k.jpg",
        "foliage_alpha": "twig_alpha_2k.jpg",
        "trunk_height": 8.0,
        "trunk_radius_base": 0.35,
        "trunk_radius_top": 0.12,
        "crown_height": 10.0,
        "crown_radius": 3.0,
        "card_count_lod0": 48,
        "card_count_lod1": 24,
        "card_count_lod2": 10,
        "card_size": 2.5,
        "conifer_spread": 0.6,
    },
    {
        "name": "fir_a",
        "type": "conifer",
        "texture_dir": os.path.join(TEXTURE_DIR, "fir_tree_01"),
        "bark_tex": "bark_diff_2k.jpg",
        "foliage_tex": "twig_diff_2k.jpg",
        "foliage_alpha": "twig_alpha_2k.jpg",
        "trunk_height": 10.0,
        "trunk_radius_base": 0.30,
        "trunk_radius_top": 0.08,
        "crown_height": 12.0,
        "crown_radius": 2.5,
        "card_count_lod0": 52,
        "card_count_lod1": 26,
        "card_count_lod2": 12,
        "card_size": 2.2,
        "conifer_spread": 0.5,
    },
    {
        "name": "broadleaf_a",
        "type": "broadleaf",
        "texture_dir": os.path.join(TEXTURE_DIR, "tree_small_02"),
        "bark_tex": "branch_diff_2k.jpg",
        "foliage_tex": "leaves_diff_2k.jpg",
        "foliage_alpha": "leaves_alpha_2k.jpg",
        "trunk_height": 5.0,
        "trunk_radius_base": 0.25,
        "trunk_radius_top": 0.10,
        "crown_height": 5.0,
        "crown_radius": 4.0,
        "card_count_lod0": 56,
        "card_count_lod1": 28,
        "card_count_lod2": 12,
        "card_size": 3.0,
        "conifer_spread": 0.0,
    },
]


def clear_scene():
    """Remove all mesh objects from the scene."""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete(use_global=False)
    # Remove orphan data
    for block in bpy.data.meshes:
        if block.users == 0:
            bpy.data.meshes.remove(block)
    for block in bpy.data.materials:
        if block.users == 0:
            bpy.data.materials.remove(block)
    for block in bpy.data.images:
        if block.users == 0:
            bpy.data.images.remove(block)


def load_texture(path):
    """Load an image texture into Blender."""
    if not os.path.exists(path):
        print(f"  WARNING: texture not found: {path}")
        return None
    img = bpy.data.images.load(path, check_existing=True)
    img.colorspace_settings.name = 'sRGB'
    return img


def create_bark_material(name, bark_image):
    """Create a PBR bark material with the given diffuse texture."""
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    output = nodes.new('ShaderNodeOutputMaterial')
    output.location = (400, 0)
    bsdf = nodes.new('ShaderNodeBsdfPrincipled')
    bsdf.location = (0, 0)
    bsdf.inputs['Roughness'].default_value = 0.85
    bsdf.inputs['Metallic'].default_value = 0.0

    if bark_image:
        tex_coord = nodes.new('ShaderNodeTexCoord')
        tex_coord.location = (-600, 0)
        mapping = nodes.new('ShaderNodeMapping')
        mapping.location = (-400, 0)
        tex_node = nodes.new('ShaderNodeTexImage')
        tex_node.location = (-200, 0)
        tex_node.image = bark_image
        tex_node.interpolation = 'Smart'
        links.new(tex_coord.outputs['UV'], mapping.inputs['Vector'])
        links.new(mapping.outputs['Vector'], tex_node.inputs['Vector'])
        links.new(tex_node.outputs['Color'], bsdf.inputs['Base Color'])
    else:
        bsdf.inputs['Base Color'].default_value = (0.17, 0.115, 0.06, 1.0)

    links.new(bsdf.outputs['BSDF'], output.inputs['Surface'])
    return mat


def create_foliage_material(name, foliage_image, alpha_image):
    """Create a PBR foliage material with alpha-masked leaf cards."""
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()

    output = nodes.new('ShaderNodeOutputMaterial')
    output.location = (600, 0)
    bsdf = nodes.new('ShaderNodeBsdfPrincipled')
    bsdf.location = (200, 0)
    bsdf.inputs['Roughness'].default_value = 0.65
    bsdf.inputs['Metallic'].default_value = 0.0

    # Alpha mask via clip
    mix_shader = nodes.new('ShaderNodeMixShader')
    mix_shader.location = (400, 0)
    transparent = nodes.new('ShaderNodeBsdfTransparent')
    transparent.location = (200, -200)
    links.new(transparent.outputs['BSDF'], mix_shader.inputs[1])
    links.new(bsdf.outputs['BSDF'], mix_shader.inputs[2])
    links.new(mix_shader.outputs['Shader'], output.inputs['Surface'])

    if foliage_image:
        tex_coord = nodes.new('ShaderNodeTexCoord')
        tex_coord.location = (-600, 0)
        mapping = nodes.new('ShaderNodeMapping')
        mapping.location = (-400, 0)
        tex_node = nodes.new('ShaderNodeTexImage')
        tex_node.location = (-200, 0)
        tex_node.image = foliage_image
        tex_node.interpolation = 'Smart'
        links.new(tex_coord.outputs['UV'], mapping.inputs['Vector'])
        links.new(mapping.outputs['Vector'], tex_node.inputs['Vector'])
        links.new(tex_node.outputs['Color'], bsdf.inputs['Base Color'])

        # Alpha texture for cutoff
        if alpha_image:
            alpha_tex = nodes.new('ShaderNodeTexImage')
            alpha_tex.location = (-200, -300)
            alpha_tex.image = alpha_image
            alpha_tex.interpolation = 'Smart'
            if alpha_image:
                alpha_image.colorspace_settings.name = 'Non-Color'
            links.new(tex_coord.outputs['UV'], mapping.inputs['Vector'])
            links.new(mapping.outputs['Vector'], alpha_tex.inputs['Vector'])

            # Use alpha channel for mix factor (clip at 0.5)
            math_node = nodes.new('ShaderNodeMath')
            math_node.operation = 'GREATER_THAN'
            math_node.location = (0, -300)
            math_node.inputs[1].default_value = 0.45
            links.new(alpha_tex.outputs['Color'], math_node.inputs[0])
            links.new(math_node.outputs['Value'], mix_shader.inputs['Fac'])
        else:
            mix_shader.inputs['Fac'].default_value = 0.0
    else:
        bsdf.inputs['Base Color'].default_value = (0.10, 0.26, 0.08, 1.0)
        mix_shader.inputs['Fac'].default_value = 0.0

    # Two-sided: disable backface culling
    mat.use_backface_culling = False
    try:
        mat.blend_method = 'CLIP'
    except (TypeError, AttributeError):
        pass
    try:
        mat.alpha_threshold = 0.45
    except (TypeError, AttributeError):
        pass

    return mat


def create_trunk(height, radius_base, radius_top, seed=42):
    """Create a tapered trunk mesh with slight curve."""
    import random
    rng = random.Random(seed)

    bpy.ops.mesh.primitive_cylinder_add(
        radius=1.0, depth=height,
        location=(0, height / 2, 0),
        vertices=12
    )
    trunk = bpy.context.active_object
    trunk.name = "trunk"

    bm = bmesh.new()
    bm.from_mesh(trunk.data)

    # Taper: scale each ring from base to top
    verts_sorted = sorted(bm.verts, key=lambda v: v.co.z)
    z_min = verts_sorted[0].co.z
    z_max = verts_sorted[-1].co.z
    z_range = z_max - z_min if z_max > z_min else 1.0

    for v in bm.verts:
        t = (v.co.z - z_min) / z_range
        r = radius_base + (radius_top - radius_base) * t
        # Add slight random lean
        lean = 0.05 * math.sin(t * math.pi) * (rng.random() - 0.5)
        v.co.x = v.co.x * r + lean
        v.co.y = v.co.y * r + lean

    bm.to_mesh(trunk.data)
    bm.free()
    bpy.ops.object.shade_smooth()
    return trunk


def create_branch(start_pos, direction, length, radius_start, radius_end, seed=0):
    """Create a single branch as a tapered cylinder."""
    import random
    rng = random.Random(seed)

    end_pos = start_pos + direction * length
    mid = (start_pos + end_pos) / 2

    bpy.ops.mesh.primitive_cylinder_add(
        radius=1.0, depth=1.0,
        location=(0, 0, 0),
        vertices=6
    )
    branch = bpy.context.active_object
    branch.name = "branch"

    bm = bmesh.new()
    bm.from_mesh(branch.data)

    # Transform to match start/end positions
    length_actual = (end_pos - start_pos).length
    for v in bm.verts:
        t = (v.co.z + 0.5)  # normalize 0..1
        r = radius_start + (radius_end - radius_start) * t
        v.co.x *= r
        v.co.y *= r
        v.co.z *= length_actual

    bm.to_mesh(branch.data)
    bm.free()

    # Orient branch along direction
    dir_vec = direction.normalized()
    rot_quat = Vector((0, 0, 1)).rotation_difference(dir_vec)
    branch.rotation_euler = rot_quat.to_euler()
    branch.location = start_pos + dir_vec * (length_actual / 2)

    bpy.ops.object.shade_smooth()
    return branch


def create_alpha_card(size, location, rotation_euler):
    """Create a single alpha card (flat quad) for foliage."""
    bpy.ops.mesh.primitive_plane_add(size=size, location=location)
    card = bpy.context.active_object
    card.name = "alpha_card"
    card.rotation_euler = rotation_euler
    return card


def place_foliage_cards(species, count, seed=42):
    """Place alpha cards in the crown volume."""
    import random
    rng = random.Random(seed)

    cards = []
    trunk_h = species["trunk_height"]
    crown_h = species["crown_height"]
    crown_r = species["crown_radius"]
    card_sz = species["card_size"]
    is_conifer = species["type"] == "conifer"
    spread = species.get("conifer_spread", 0.0)

    for i in range(count):
        # Vertical position within crown
        t = rng.random()
        y = trunk_h + t * crown_h

        if is_conifer:
            # Conifer: radius decreases with height (cone shape)
            max_r = crown_r * (1.0 - t * spread)
            r = max_r * math.sqrt(rng.random())
        else:
            # Broadleaf: ellipsoidal crown, widest at 40% height
            crown_t = t
            width_factor = math.sin(crown_t * math.pi) ** 0.6
            max_r = crown_r * width_factor
            r = max_r * math.sqrt(rng.random())

        # Azimuth
        theta = rng.random() * 2 * math.pi
        x = r * math.cos(theta)
        z = r * math.sin(theta)

        # Random rotation for variety
        rx = rng.random() * math.pi
        ry = rng.random() * math.pi
        rz = theta + rng.gauss(0, 0.3)

        # Vary card size slightly
        sz = card_sz * (0.7 + 0.6 * rng.random())

        card = create_alpha_card(sz, (x, z, y), (rx, ry, rz))
        cards.append(card)

    return cards


def build_tree(species, lod_level, seed=42):
    """Build a complete tree for the given LOD level."""
    import random
    rng = random.Random(seed)

    lod_scale = {0: 1.0, 1: 0.65, 2: 0.35}[lod_level]
    card_counts = {
        0: species["card_count_lod0"],
        1: species["card_count_lod1"],
        2: species["card_count_lod2"],
    }
    n_cards = int(card_counts[lod_level] * lod_scale)
    n_cards = max(n_cards, 4)

    # Trunk
    trunk_subdivisions = {0: 12, 1: 8, 2: 6}[lod_level]
    bpy.ops.mesh.primitive_cylinder_add(
        radius=1.0,
        depth=species["trunk_height"],
        location=(0, 0, species["trunk_height"] / 2),
        vertices=trunk_subdivisions
    )
    trunk = bpy.context.active_object
    trunk.name = f"trunk_lod{lod_level}"

    bm = bmesh.new()
    bm.from_mesh(trunk.data)
    verts_sorted = sorted(bm.verts, key=lambda v: v.co.z)
    z_min = verts_sorted[0].co.z
    z_max = verts_sorted[-1].co.z
    z_range = z_max - z_min if z_max > z_min else 1.0

    for v in bm.verts:
        t = (v.co.z - z_min) / z_range
        r_base = species["trunk_radius_base"]
        r_top = species["trunk_radius_top"]
        r = r_base + (r_top - r_base) * t
        lean = 0.03 * math.sin(t * math.pi * 1.5) * (rng.random() - 0.5)
        v.co.x = v.co.x * r + lean
        v.co.y = v.co.y * r + lean

    bm.to_mesh(trunk.data)
    bm.free()
    bpy.ops.object.shade_smooth()

    # Branches (LOD0 and LOD1 only)
    branches = []
    if lod_level <= 1:
        n_branches = {0: 6, 1: 3}[lod_level]
        for i in range(n_branches):
            t = 0.3 + 0.5 * (i / max(n_branches - 1, 1))
            branch_y = species["trunk_height"] * t
            angle = (i / n_branches) * 2 * math.pi + rng.gauss(0, 0.3)
            direction = Vector((math.cos(angle), math.sin(angle), 0.3 + 0.4 * rng.random())).normalized()
            branch_len = species["crown_radius"] * (0.4 + 0.3 * rng.random()) * lod_scale
            r_start = species["trunk_radius_base"] * 0.3 * (1 - t * 0.5)
            branch = create_branch(
                Vector((0, 0, branch_y)),
                direction, branch_len, r_start, r_start * 0.3,
                seed=seed + i
            )
            branches.append(branch)

    # Foliage alpha cards
    cards = place_foliage_cards(species, n_cards, seed=seed)

    return trunk, branches, cards


def export_glb(filepath, bark_mat, foliage_mat):
    """Export the scene to GLB with proper materials."""
    # Assign materials
    for obj in bpy.context.scene.objects:
        if obj.type != 'MESH':
            continue
        if 'trunk' in obj.name or 'branch' in obj.name:
            if obj.data.materials:
                obj.data.materials[0] = bark_mat
            else:
                obj.data.materials.append(bark_mat)
        elif 'card' in obj.name:
            if obj.data.materials:
                obj.data.materials[0] = foliage_mat
            else:
                obj.data.materials.append(foliage_mat)

    # Join bark parts and foliage parts separately for 2-primitive GLB
    bark_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH' and ('trunk' in o.name or 'branch' in o.name)]
    foliage_objects = [o for o in bpy.context.scene.objects if o.type == 'MESH' and 'card' in o.name]

    # Select and join bark
    bpy.ops.object.select_all(action='DESELECT')
    for obj in bark_objects:
        obj.select_set(True)
    if bark_objects:
        bpy.context.view_layer.objects.active = bark_objects[0]
        bpy.ops.object.join()
        bark_obj = bpy.context.active_object
        bark_obj.name = "bark"

    # Select and join foliage
    bpy.ops.object.select_all(action='DESELECT')
    for obj in foliage_objects:
        obj.select_set(True)
    if foliage_objects:
        bpy.context.view_layer.objects.active = foliage_objects[0]
        bpy.ops.object.join()
        foliage_obj = bpy.context.active_object
        foliage_obj.name = "foliage"

    # Apply all transforms
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

    # Export
    bpy.ops.export_scene.gltf(
        filepath=filepath,
        export_format='GLB',
        use_selection=False,
        export_apply=True,
        export_materials='EXPORT',
    )

    return filepath


def process_species(species):
    """Process one species: build all LODs and export GLBs."""
    name = species["name"]
    tex_dir = species["texture_dir"]

    print(f"\n{'='*60}")
    print(f"Processing: {name}")
    print(f"{'='*60}")

    # Load textures
    bark_path = os.path.join(tex_dir, species["bark_tex"])
    foliage_path = os.path.join(tex_dir, species["foliage_tex"])
    alpha_path = os.path.join(tex_dir, species["foliage_alpha"])

    bark_img = load_texture(bark_path)
    foliage_img = load_texture(foliage_path)
    alpha_img = load_texture(alpha_path)

    print(f"  Textures loaded: bark={bark_img is not None}, foliage={foliage_img is not None}, alpha={alpha_img is not None}")

    for lod in range(3):
        clear_scene()

        # Re-load textures after clear (they may be orphaned)
        bark_img = load_texture(bark_path)
        foliage_img = load_texture(foliage_path)
        alpha_img = load_texture(alpha_path)

        # Create materials
        bark_mat = create_bark_material(f"{name}_bark_lod{lod}", bark_img)
        foliage_mat = create_foliage_material(f"{name}_foliage_lod{lod}", foliage_img, alpha_img)

        # Build tree
        seed = hash(name) & 0xFFFF
        trunk, branches, cards = build_tree(species, lod, seed=seed)

        print(f"  LOD{lod}: trunk + {len(branches)} branches + {len(cards)} cards")

        # Count triangles
        tri_count = 0
        for obj in bpy.context.scene.objects:
            if obj.type == 'MESH':
                mesh = obj.data
                tri_count += len(mesh.polygons)
        print(f"  LOD{lod}: ~{tri_count} triangles")

        # Export
        output_path = os.path.join(OUTPUT_DIR, f"field_{name}_lod{lod}.glb")
        export_glb(output_path, bark_mat, foliage_mat)
        print(f"  Exported: {output_path}")


def main():
    print("PV1-R Production Vegetation Asset Generator")
    print(f"Texture directory: {TEXTURE_DIR}")
    print(f"Output directory: {OUTPUT_DIR}")

    for species in SPECIES:
        process_species(species)

    print(f"\n{'='*60}")
    print("All species processed successfully!")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
